spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud_db
    username: crud_user
    password: crud123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
